language: cpp
sudo: false

#env:
#matrix:
    #- COMPILER=g++
    #- COMPILER=clang++

git:
  depth: 1
addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - gcc-5
      - clang-3.8

before_script:
  - mkdir build
  - cd build
  - cmake .. #-DCMAKE_CXX_COMPILER=${COMPILER}

script:
  - make -j2
  - make test
